# run with treefmt --allow-missing-formatter

[global]
excludes = [
  # go.sum & go.mod
  "go.sum",
  "go.mod",
  # gitignore
  "**/.gitignore",
  # longdrift docs
  "tools/longdrift/README.md",
  "tools/calibrate/README.md",
]

### Go

[formatter.gofumpt]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]

[formatter.gci]
command = "gci"
options = ["-w"]
includes = ["*.go"]
priority = 1  # run after gofumpt

### Markdown

[formatter.markdownlint]
command = "markdownlint"
options = ["--fix"]
includes = ["*.md"]

[formatter.prettier]
command = "prettier"
options = ["-w"]
includes = ["*.md"]
priority = 1 # run after markdownlint
